# Generated by Django 4.0.3 on 2022-03-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_news_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='img',
            field=models.ImageField(default=1, upload_to='images/news'),
            preserve_default=False,
        ),
    ]
